module.exports = {
    IO_DISCONNECT: 'disconnect',
    IO_DISCONNECTING: 'disconnecting',


    CREATE_AND_JOIN_LOBBY: "CREATE_AND_JOIN_LOBBY",
    
    JOIN_LOBBY: "JOIN_LOBBY",
    LEAVE_LOBBY: "LEAVE_LOBBY",
    UPDATE_PLAYER_LIST: "UPDATE_PLAYER_LIST",
    LOBBY_EXISTS: "LOBBY_EXISTS",
    GET_PLAYER_LIST: "GET_PLAYER_LIST",

    GET_LOBBY_SETTINGS: "GET_LOBBY_SETTINGS",
    UPDATE_LOBBY_SETTINGS: "UPDATE_LOBBY_SETTINGS",
    SUBMIT_LOBBY_SETTINGS: "SUBMIT_LOBBY_SETTINGS",


    
    PICK_IMPOSTERS: "PICK_IMPOSTERS",
    GET_IMPOSTERS: "GET_IMPOSTERS",
    START_GAME: "START_GAME",
   

    PICK_RANDOM_TASK: 'PICK_RANDOM_TASK',
    SWITCH_SCREEN: 'SWITCH_SCREEN',
    SEND_ANSWER: 'SEND_ANSWER',
    SHOW_ANSWERS: 'SHOW_ANSWERS',
    END_GAME: 'END_GAME',
}